apiVersion: apps/v1
kind: Deployment
metadata:
  name: hiring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hiring-app
  template:
    metadata:
      labels:
        app: hiring-app
    spec:
      containers:
      - name: hiring-app
        image:  santhu123456/hiring-app:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hiring-app-service
spec:
  type: NodePort
  selector:
    app: hiring-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
